from typing import Protocol
from modulo_auth.refresh_token_entity import RefreshTokenEntity

class RefreshTokenRepository(Protocol):
    def create(self, user_id, token_hash, device_info, expires_at) -> RefreshTokenEntity: ...
    def get_by_hash(self, token_hash) -> RefreshTokenEntity: ...
    def revoke(self, id): ...
    def revoke_all_for_user(self, user_id): ...